AWSTemplateFormatVersion: 2010-09-09
Description: Compute Benchmarks - Infra (common resources)

Resources:
  BenchmarkImage:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: benchmark
      Tags:
        - { Key: Name, Value: benchmark }
